# fly.toml app configuration file generated for acme-server on 2024-06-16T14:57:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'acme-server'
primary_region = 'ord'

[build]
  dockerfile = './apps/server/Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
